---
trigger:
  name: daily
  identifier: daily
  enabled: true
  stagesToExecute: []
  tags: {}
  orgIdentifier: No_Code_Apps
  projectIdentifier: dataanalyst
  pipelineIdentifier: trivyScan
  source:
    type: Scheduled
    spec:
      type: Cron
      spec:
        expression: 0 8 * * *
        type: UNIX
  inputYaml: |
    pipeline:
      identifier: trivyScan
      properties:
        ci:
          codebase:
            build:
              type: branch
              spec:
                branch: main
