---
trigger:
  name: GitHub
  identifier: GitHub
  enabled: true
  stagesToExecute: []
  description: ""
  tags: {}
  encryptedWebhookSecretIdentifier: ""
  orgIdentifier: No_Code_Apps
  projectIdentifier: dataanalyst
  pipelineIdentifier: trivyScan
  source:
    type: Webhook
    spec:
      type: Github
      spec:
        type: PullRequest
        spec:
          connectorRef: account.svc_harness_git1
          autoAbortPreviousExecutions: false
          payloadConditions:
            - key: changedFiles
              operator: Equals
              value: requirements.txt
          headerConditions: []
          repoName: recipe-bob
          actions:
            - Open
            - Synchronize
  inputYaml: |
    pipeline:
      identifier: trivyScan
      properties:
        ci:
          codebase:
            build:
              type: branch
              spec:
                branch: <+trigger.branch>
